# Generated by Django 4.1.5 on 2023-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hit_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
