# Generated by Django 4.1.5 on 2023-01-27 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_news_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='remark',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
