# Generated by Django 4.1.5 on 2023-01-28 12:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_news_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='remark',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
