# Generated by Django 4.1.5 on 2023-02-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_alter_news_hit_count_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='hit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='categories', to='core.category', verbose_name='Category'),
        ),
    ]
