# Generated by Django 4.1.5 on 2023-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news_main_remove_news_category_alter_news_hit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
