# Generated by Django 4.1.5 on 2023-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
