# Generated by Django 4.1.5 on 2023-02-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_news_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner_image_small',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Big Banner image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Big Banner image'),
        ),
    ]
