# Generated by Django 4.1.5 on 2023-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_news_banner_image_small_alter_news_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='banner_image_small',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Small Banner image'),
        ),
    ]
