# Generated by Django 4.1.5 on 2023-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_news_banner_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='news', to='core.category', verbose_name='Category'),
        ),
    ]
