# Generated by Django 4.1.5 on 2023-02-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
