# Generated by Django 4.1.5 on 2023-03-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='news',
            new_name='contents',
        ),
    ]
