# Generated by Django 4.1.5 on 2023-03-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_news_content_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.news', verbose_name='Content'),
        ),
    ]
