# Generated by Django 4.1.5 on 2023-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_content_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AddField(
            model_name='content',
            name='video_link',
            field=models.CharField(max_length=5000, null=True, verbose_name='Title'),
        ),
    ]
