# Generated by Django 4.1.5 on 2023-03-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_content_options_content_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_link',
            field=models.CharField(max_length=5000, null=True, verbose_name='YouTube video link'),
        ),
    ]
