# Generated by Django 4.1.5 on 2023-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_content_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='content',
            name='url_name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='URL name'),
        ),
    ]
