# Generated by Django 4.1.5 on 2023-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_content_url_content_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_title',
            field=models.CharField(max_length=3000, null=True, verbose_name='Short Description'),
        ),
    ]
